spring:
  datasource:
    url: jdbc:h2:mem:test
    username: switchwon
    password: switchwon12
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data_init.sql
