DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS merchant;
DROP TABLE IF EXISTS balance;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS credit_card_payment;
DROP TABLE IF EXISTS commission_rate;

CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    user_id VARCHAR(5) UNIQUE NOT NULL COMMENT '사용자 ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE merchant(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    merchant_id VARCHAR(20) NOT NULL COMMENT '대상(업체)명',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE balance(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    user_id VARCHAR(5) UNIQUE NOT NULL COMMENT '사용자 ID',
    balance NUMERIC(10,2) NOT NULL COMMENT '잔액',
    currency VARCHAR(5) NOT NULL COMMENT '통화',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE credit_card_payment(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    card_number VARCHAR(20) COMMENT '카드번호',
    expiry_date VARCHAR(5) COMMENT '카드 만료일자',
    cvv SMALLINT NOT NULL COMMENT '카드 CVV 번호',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '카드 활성 상태 (0: 비활성화, 1: 활성화)' ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE commission_rate(
    id INTEGER AUTO_INCREMENT PRIMARY KEY ,
    merchant_id VARCHAR(20) NOT NULL COMMENT '대상(업체)',
    commission_type VARCHAR(10) NOT NULL COMMENT '수수료 종류(FIXED,PERCENTAGE)',
    amount NUMERIC(10,2) default 0 COMMENT '수수료 금액',
    rate NUMERIC(10,2) default 0 COMMENT '수수료 퍼센트',
    status TINYINT DEFAULT 0 NOT NULL COMMENT '수수료 적용 상태(0: 비활성화, 1: 활성화)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE payment(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    payment_id VARCHAR(20) NOT NULL COMMENT '결제 번호',
    user_id VARCHAR(5) NOT NULL COMMENT '사용자 ID',
    payment_method VARCHAR(20) NOT NULL COMMENT '결제 방법',
    amount NUMERIC(10,2) NOT NULL COMMENT '결제금액',
    currency VARCHAR(5) NOT NULL COMMENT '결제통화',
    merchant_id VARCHAR(20) NOT NULL COMMENT '대상(업체)',
    credit_card_id BIGINT NOT NULL COMMENT '결제수단 정보 테이블 ID',
    commission_id BIGINT NOT NULL COMMENT '결재대상 수수료 테이블',
    approval_status VARCHAR(10) DEFAULT 'WAITING' NOT NULL COMMENT '결제 상태',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (credit_card_id) REFERENCES credit_card_payment(id),
    FOREIGN KEY (commission_id) REFERENCES commission_rate(id)
);
